[air_heuristic]
    network_path = "data/es_full_AW/"
    flight_schedules = "flight_schedules_oag_es.csv"
    airports_static = "infrastructure/airports_static.csv"
    dist_range = '[(0, 150, None), (150, 2000, 100), (2000, 99999, 500)]'

[rail_heuristic]
    gtfs_path = "data/es_full_AW/gtfs_es_20220708"
    #rail_stations_considered = 'data/example_strategic/es/rail_stations_considered.csv'
    rail_stations_considered_nuts = 'output/data_analysis/nuts3_ES_filtered.csv'
    country = 'ES'
    date = '20220923'
    interval_range = 50

[output]
	output_folder = "data/es_full_AW/processed/heuristics_computed/"
