[network_definition]
    network_path = "../../data/example_strategic/es/"
    processed_folder = "processed"
    [network_definition.air_network]
        flight_schedules = "flight_schedules.csv"
        airports_static = "airports_static.csv"
		mct_air = "mct_air.csv"
    [network_definition.rail_network]
        gtfs = "gtfs_es"
        rail_stations_considered = "rail_stations_considered.csv"
        create_rail_layer_from = 'gtfs' #gtfs / services
    [network_definition.multimodal]
        air_rail_transitions = "air_rail_transitions.csv"
	[network_definition.regions_access]
		regions_access = "regions_access.csv"

[demand]
	demand = "../../data/example_strategic/es/pax_demand.csv"

[output]
	output_folder = "../../data/example_strategic/es/processed/possible_paths/"