[network_definition]
    network_path = "../../data/CS-ES/v=0.7/"
    processed_folder = "processed"
    [[network_definition.air_network]]
        flight_schedules = "flights_schedules/flight_schedules_oag_es.csv"
        alliances = "flights_schedules/air_alliances.csv"
        airports_static = "infrastructure/airports_coordinates_v1.1.csv"
        mct_air = "infrastructure/mct_air_v0.2.csv"
        mct_default = 30
    [[network_definition.rail_network]]
        gtfs = "gtfs_es_UIC"
        date_rail = "20230920" # Date to use to filter GTFS
        date_to_set_rail = "20190906" # Date from flights to make rail and flights 'compatible'
        rail_stations_considered = "infrastructure/rail_stations_considered_GTFS_2022.csv"
        mct_rail = "infrastructure/mct_rail_v0.1.csv"
        mct_default = 15
        create_rail_layer_from = 'services' #gtfs / services
        country = "LE"
    [[network_definition.processing_time]]
        airport_processes = "infrastructure/airport_processes_v0.1.csv"
        iata_icao_static = "infrastructure/IATA_ICAO_Airport_codes_v1.3.csv"
        rail_stations_processes = "infrastructure/rail_stations_processes_v0.1.csv"
        default_process_time_k2g = 90
        default_process_time_g2k = 30
        default_process_time_k2p = 15
        default_process_time_p2k = 10
    [[network_definition.multimodal]]
        air_rail_transitions = "infrastructure/air_rail_transitions_v0.1.csv"
	[[network_definition.regions_access]]
		regions_access = "infrastructure/regions_access_v0.1.csv"
        iata_icao_static = "infrastructure/IATA_ICAO_Airport_codes_v1.3.csv"

[demand]
    demand = "../../data/CS-ES/v=0.7/demand/pax_demand_mobile_phone.csv"


[sensitivities]
    sensitivities = "../../data/CS-ES/v=0.7/sensitivities"

[other_param]
    [other_param.kpi_cluster_itineraries]
        # Can define, or not kpis_to_use for the clustering of itineraries
        # Then, thresholds can be provided. if category doesn't exit (e.g. no rail, or no some
        # kpi for some cateogy), the values from 'all' will be taken (if given)
        # if nothing is provided, the thershold will be computed as the std of the kpi for the
        # category being clustered
        kpis_to_use = ['total_travel_time', 'total_cost', 'total_emissions', 'total_waiting_time', 'nservices']
        [other_param.kpi_cluster_itineraries.thresholds.all]
            total_cost = 30
            total_travel_time = 50
            total_emissions = 15
            total_waiting_time = 30
            nservices = 0
        [other_param.kpi_cluster_itineraries.thresholds.air]
            total_emissions = 20

    [other_param.thresholds_pareto_dominance]
        total_travel_time = 15
        total_cost = 10
        total_emissions = 5
        total_waiting_time = 30

    [other_param.sensitivities_logit]
        sensitivities = "../../data/CS-ES/v=0.7/sensitivities"
[output]
	output_folder = "../../data/CS-ES/v=0.7/processed/paths_itineraries/"

#  python ./strategic_pipeline.py -tf ../../data/CS-ES/v=0.7/es.toml -ni 50 -np 100 -mc 1 -hpc -pc 23  -lf ./test_loggin.log -v